# Generated by Django 5.1.2 on 2024-10-19 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stockpriceprediction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockpriceprediction',
            old_name='symbol',
            new_name='stock_symbol',
        ),
    ]
